# Generated by Django 4.2.5 on 2023-09-21 01:16

from django.db import migrations


CREATE_CURSOS_TABLE = '''
CREATE TABLE IF NOT EXISTS cursos(
    id bigserial PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT current_timestamp
);
'''
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cursos_option_to_managed'),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_CURSOS_TABLE,
            'DROP TABLE IF EXISTS cursos;'
        )
    ]
